fix

diff --git a/omr-tracker/files/bin/omr-tracker b/omr-tracker/files/bin/omr-tracker
--- a/omr-tracker/files/bin/omr-tracker
+++ b/omr-tracker/files/bin/omr-tracker
@@ -24,6 +24,7 @@ export OMR_TRACKER_STATUS
 export OMR_TRACKER_STATUS_MSG
 export OMR_TRACKER_PREV_STATUS
 export OMR_TRACKER_DEVICE
+export OMR_TRACKER_PREV_DEVICE
 export OMR_TRACKER_DEVICE_IP
 export OMR_TRACKER_DEVICE_IP6
 export OMR_TRACKER_PREV_DEVICE_IP
@@ -35,6 +36,7 @@ export OMR_TRACKER_PROTO
 export OMR_TRACKER_INTERVAL_TRIES
 export OMR_TRACKER_INTERVAL
 export OMR_TRACKER_NO_BIND
+export OMR_TRACKER_TYPE
 
 #dscp=56   # set DSCP CS7 (56) in outgoing packets
 
@@ -117,12 +119,29 @@ _ping_server() {
 				statusp=$?
 				if $(exit $statusp); then
 					serverip_ping=true
-					return
+					return 0
 				fi
 			fi
 		}
 		config_load openmptcprouter
 		config_list_foreach "${servername}" ip check_ping
+	fi
+}
+
+_ping_server_all() {
+	count_server() {
+		config_get disabled $1 disabled
+		config_get serverip $1 ip
+		if [ "$disabled" != "1" ] && [ -n "$serverip" ]; then
+			servers=true
+		fi
+	}
+	config_load openmptcprouter
+	config_foreach count_server server
+	if [ "$servers" = true ]; then
+		for intf in $(multipath 2>/dev/null | awk '/default/ { print $1 }); do
+			config_foreach _ping_server server $intf
+		done
 	fi
 }
 
@@ -140,7 +159,7 @@ _httping_server() {
 				statusp=$?
 				if $(exit $statusp); then
 					serverip_ping=true
-					return
+					return 0
 				fi
 			fi
 		}
@@ -148,6 +167,24 @@ _httping_server() {
 		config_list_foreach "${servername}" ip check_ping
 	fi
 }
+
+_httping_server_all() {
+	count_server() {
+		config_get disabled $1 disabled
+		config_get serverip $1 ip
+		if [ "$disabled" != "1" ] && [ -n "$serverip" ]; then
+			servers=true
+		fi
+	}
+	config_load openmptcprouter
+	config_foreach count_server server
+	if [ "$servers" = true ]; then
+		for intf in $(multipath 2>/dev/null | awk '/default/ { print $1 }); do
+			config_foreach _httping_server server $intf
+		done
+	fi
+}
+
 
 _ping() {
 	local host="$1"
@@ -163,7 +200,8 @@ _ping() {
 			-Q 184 \
 			"${host}" 2>&1
 		)
-		loss=$(echo "$ret" | awk '/packet loss/ {gsub("%","");print $6}' | tr -d '\n')
+		loss=$(echo "$ret" | awk '/packet loss/ && !/errors/ {gsub("%","");print $6}' | tr -d '\n')
+		
 		if [ -n "$loss" ] && [ "$loss" != "100" ]; then
 			if [ "$localip" = "yes" ]; then
 				latency=$(echo "$ret" | awk -F/ '/rtt/ {print int($5)}' | tr -d '\n')
@@ -173,7 +211,7 @@ _ping() {
 				}
 				OMR_TRACKER_LOSS="$loss"
 			fi
-			return
+			return 0
 		fi
 	else
 		ret=$(ping -B -I "${device}" \
@@ -186,9 +224,7 @@ _ping() {
 		)
 		bindcheck=$(echo "$ret" | grep "Address not available")
 		[ -n "$bindcheck" ] && OMR_TRACKER_NO_BIND=1
-		#loss=$(echo "$ret" | grep 'packet loss' | sed -ne 's/.*\([0-9]\+\)% packet loss.*/\1/p')
-		#loss=$(echo "$ret" | grep 'packet loss' | cut -d " " -f6 | sed 's/%//' | tr -d '\n')
-		loss=$(echo "$ret" | awk '/packet loss/ {gsub("%","");print $6}' | tr -d '\n')
+		loss=$(echo "$ret" | awk '/packet loss/ && !/errors/  {gsub("%","");print $6}' | tr -d '\n')
 		if [ -n "$loss" ] && [ "$loss" != "100" ]; then
 			if [ "$localip" = "yes" ]; then
 				#latency=$(echo "$ret" | grep rtt | cut -d "/" -s -f5 | cut -d "." -f1 | tr -d '\n')
@@ -199,13 +235,12 @@ _ping() {
 				}
 				OMR_TRACKER_LOSS="$loss"
 			fi
-			return
+			return 0
 		fi
-		#) && echo "$ret" | grep -sq "bytes from" && {
 	fi
-	false
+	return 1
 }
-
+#'
 _httping() {
 	local host=$1
 	local deviceip=$2
@@ -216,27 +251,43 @@ _httping() {
 			-y "${deviceip}" \
 			-t "$OMR_TRACKER_TIMEOUT" \
 			-c "$OMR_TRACKER_COUNT" 2>&1
-		) && echo "$ret" | grep -sq "1 ok" && {
+		)
+		bindcheck=$(echo "$ret" | grep "Address not available")
+		[ -n "$bindcheck" ] && OMR_TRACKER_NO_BIND=1
+		loss=$(echo "$ret" | awk '/failed/ {gsub("%",""); print int($5)}' | tr -d '\n')
+		if [ -n "$loss" ] && [ "$loss" != "100" ]; then
 			if [ "$localip" = "yes" ]; then
-				OMR_TRACKER_LATENCY=$(echo "$ret" | cut -d "/" -s -f5 | cut -d "." -f1 | tr -d '\n')
-				#_update_rto "$OMR_TRACKER_LATENCY"
+				latency=$(echo "$ret" | cut -d "/" -s -f5 | cut -d "." -f1 | tr -d '\n')
+				[ -n "$latency" ] && {
+					OMR_TRACKER_LATENCY="$latency"
+					#_update_rto "$OMR_TRACKER_LATENCY"
+				}
+				OMR_TRACKER_LOSS="$loss"
 			fi
-			return
-		}
+			return 0
+		fi
 	else
 		ret=$(httping -l "${host}" \
 			-y "${deviceip}" \
 			-t "$OMR_TRACKER_TIMEOUT" \
 			-c "$OMR_TRACKER_COUNT" 2>&1
-		) && echo "$ret" | grep -sq "1 ok" && {
+		)
+		bindcheck=$(echo "$ret" | grep "Address not available")
+		[ -n "$bindcheck" ] && OMR_TRACKER_NO_BIND=1
+		loss=$(echo "$ret" | awk '/failed/ {gsub("%",""); print int($5)}' | tr -d '\n')
+		if [ -n "$loss" ] && [ "$loss" != "100" ]; then
 			if [ "$localip" = "yes" ]; then
-				OMR_TRACKER_LATENCY=$(echo "$ret" | cut -d "/" -s -f5 | cut -d "." -f1 | tr -d '\n')
-				#_update_rto "$OMR_TRACKER_LATENCY"
+				latency=$(echo "$ret" | cut -d "/" -s -f5 | cut -d "." -f1 | tr -d '\n')
+				[ -n "$latency" ] && {
+					OMR_TRACKER_LATENCY="$latency"
+					#_update_rto "$OMR_TRACKER_LATENCY"
+				}
+				OMR_TRACKER_LOSS="$loss"
 			fi
-			return
-		}
+			return 0
+		fi
 	fi
-	false
+	return 1
 }
 
 _dns() {
@@ -247,22 +298,24 @@ _dns() {
 		    +time="$OMR_TRACKER_TIMEOUT" \
 		    +tries="$OMR_TRACKER_COUNT" \
 		    one.one.one.one
-	) && echo "$ret" | grep -sq "223.5.5.5" && {
+	) && echo "$ret" | grep -sq "1.1.1.1" && {
 		OMR_TRACKER_LATENCY=$(echo "$ret" | awk '/Query time/{print $4}')
 		#_update_rto "$OMR_TRACKER_LATENCY"
-		return
+		return 0
 	}
-	false
+	return 1
 }
 
 _none() {
-	return
+	return 0
 }
 
 _restart
 
 OMR_TRACKER_INTERFACE_PROTO="$(uci -q get network.${OMR_TRACKER_INTERFACE}.proto)"
 OMR_TRACKER_PREV_STATUS=""
+[ "$OMR_TRACKER_INTERFACE_PROTO" = "modemmanager" ] && sleep $(uci -q get network.${OMR_TRACKER_INTERFACE}.delay || echo '120')
+
 # main loop
 while true; do
 	# setup tracker variables
@@ -278,15 +331,16 @@ while true; do
 	OMR_TRACKER_DEVICE_GATEWAY6=
 	serverip_ping=false
 	[ -z "$OMR_TRACKER_DEVICE" ] || [ -d "/sys/class/net/$OMR_TRACKER_DEVICE" ] && {
-			network_get_physdev OMR_TRACKER_DEVICE "$OMR_TRACKER_INTERFACE"
-			[ -z "$OMR_TRACKER_DEVICE" ] && network_get_device OMR_TRACKER_DEVICE "$OMR_TRACKER_INTERFACE"
 			[ -z "$OMR_TRACKER_DEVICE" ] && OMR_TRACKER_DEVICE=$(ifstatus "$OMR_TRACKER_INTERFACE" | jsonfilter -q -e '@["l3_device"]')
 			[ -z "$OMR_TRACKER_DEVICE" ] && OMR_TRACKER_DEVICE=$(ifstatus "${OMR_TRACKER_INTERFACE}_4" | jsonfilter -q -e '@["l3_device"]')
 			#[ -z "$OMR_TRACKER_DEVICE" ] && config_get OMR_TRACKER_DEVICE "$OMR_TRACKER_INTERFACE" device
 			[ -n "$(echo $OMR_TRACKER_DEVICE | grep '@')" ] && OMR_TRACKER_DEVICE=$(ifstatus "$OMR_TRACKER_INTERFACE" | jsonfilter -q -e '@["device"]')
+			[ -z "$OMR_TRACKER_DEVICE" ] && network_get_physdev OMR_TRACKER_DEVICE "$OMR_TRACKER_INTERFACE"
+			[ -z "$OMR_TRACKER_DEVICE" ] && network_get_device OMR_TRACKER_DEVICE "$OMR_TRACKER_INTERFACE"
 	}
 
 	if [ -n "$OMR_TRACKER_DEVICE" ] && [ -d "/sys/class/net/$OMR_TRACKER_DEVICE" ]; then
+		OMR_TRACKER_PREV_DEVICE="$OMR_TRACKER_DEVICE"
 		OMR_TRACKER_DEVICE_STATE=$(ip -j link show dev "$OMR_TRACKER_DEVICE" | jsonfilter -q -e '@[*].operstate' | tr -d '\n')
 		if ([ "$(ifstatus $OMR_TRACKER_INTERFACE | jsonfilter -q -e '@.up')" == "true" ] && [ "$OMR_TRACKER_DEVICE_STATE" != "DOWN" ]) || [ "$OMR_TRACKER_INTERFACE" = "omrvpn" ]; then
 			# retrieve iface ip and gateway
@@ -324,7 +378,7 @@ while true; do
 					fi
 				fi
 				if [ -z "$OMR_TRACKER_DEVICE_GATEWAY" ]; then
-					OMR_TRACKER_DEVICE_ROUTE=$(ip -4 r list dev "$OMR_TRACKER_DEVICE" | grep via | grep -v default | grep -v metric | grep -v / | awk '{print $1; exit}' | tr -d "\n")
+					OMR_TRACKER_DEVICE_ROUTE=$(ip -4 r list dev "$OMR_TRACKER_DEVICE" | grep via | grep -v default | grep -v nexthop | grep -v metric | grep -v / | awk '{print $1; exit}' | tr -d "\n")
 				fi
 				if [ -z "$OMR_TRACKER_DEVICE_GATEWAY" ]; then
 					OMR_TRACKER_DEVICE_GATEWAY=$(ip -4 r list dev "$OMR_TRACKER_DEVICE" | grep kernel | grep -v '.0/' | awk '/proto kernel/ {print $1;exit}' | tr -d "\n")
@@ -335,6 +389,10 @@ while true; do
 				if [ -z "$OMR_TRACKER_DEVICE_GATEWAY" ]; then
 					OMR_TRACKER_DEVICE_GATEWAY=$(ip -4 r list dev "$OMR_TRACKER_DEVICE" | awk '/via/ {print $3;exit}' | tr -d "\n")
 				fi
+				if [ -z "$OMR_TRACKER_DEVICE_GATEWAY" ] && [ "$OMR_TRACKER_INTERFACE" = "omrvpn" ] && [ "$(uci -q get openvpn.omr.enabled)" = "1" ]; then
+					OMR_TRACKER_DEVICE_GATEWAY="10.255.252.1"
+				fi
+
 			fi
 			if { [ "$OMR_TRACKER_IPV6" = "1" ] || [ "$OMR_TRACKER_IPV6" = "auto" ]; } && { [ "$OMR_TRACKER_FAMILY" = "ipv6" ] || [ "$OMR_TRACKER_FAMILY" = "ipv4ipv6" ]; }; then
 				#OMR_TRACKER_DEVICE_IP6=$(ip -6 -br addr ls dev "$OMR_TRACKER_DEVICE" | awk -F'[ /]+' '{print $3}')
@@ -371,6 +429,17 @@ while true; do
 				fi
 				# loop until tries attempts have been reached
 				while [ "$tries" -gt 0 ]; do
+					if [ "$OMR_TRACKER_TYPE" = "glorytun-udp" ]; then
+						glorytun_state="$(glorytun-udp path addr $OMR_TRACKER_DEVICE_IP | awk '/path/ { print $4 }' | tr -d '\n')"
+						if [ "$glorytun_state" = "running" ]; then
+							OMR_TRACKER_STATUS_MSG=""
+							OMR_TRACKER_STATUS="OK"
+						else
+							OMR_TRACKER_STATUS_MSG="Glorytun-UDP path $OMR_TRACKER_DEVICE_IP ($OMR_TRACKER_INTERFACE) is $glorytun_state"
+							OMR_TRACKER_STATUS="ERROR"
+						fi
+						break
+					fi
 					if [ -n "$OMR_TRACKER_DEVICE_ROUTE" ]; then
 						_ping "$OMR_TRACKER_DEVICE_ROUTE" "$OMR_TRACKER_DEVICE" "no"
 						status=$?
@@ -384,7 +453,7 @@ while true; do
 						break
 					elif [ "$OMR_TRACKER_TYPE" != "none" ]; then
 						if ! $(exit $status); then
-							OMR_TRACKER_STATUS_MSG="gateway down"
+							OMR_TRACKER_STATUS_MSG="IPv4 gateway down"
 						fi
 						serverip_ping=false
 						if [ "$OMR_TRACKER_TYPE" = "ping" ]; then
@@ -420,7 +489,7 @@ while true; do
 								fi
 								[ -n "$(ip route show ${OMR_TRACKER_HOST} via ${OMR_TRACKER_DEVICE_GATEWAY} dev ${OMR_TRACKER_DEVICE} src ${OMR_TRACKER_DEVICE_IP})" ] && ip route del "$OMR_TRACKER_HOST" via "$OMR_TRACKER_DEVICE_GATEWAY" dev "$OMR_TRACKER_DEVICE" src "$OMR_TRACKER_DEVICE_IP" > /dev/null 2>&1
 								if $(exit $statusb); then
-									OMR_TRACKER_STATUS_MSG=""
+									#OMR_TRACKER_STATUS_MSG=""
 									OMR_TRACKER_STATUS="OK"
 								else
 									if [ "$OMR_TRACKER_LIST_HOSTS" = "" ]; then
@@ -430,12 +499,9 @@ while true; do
 									fi
 									OMR_TRACKER_STATUS_MSG="check error"
 								fi
-							else
-								OMR_TRACKER_STATUS_MSG=""
-								OMR_TRACKER_STATUS="OK"
 							fi
 						else
-							OMR_TRACKER_STATUS_MSG=""
+							#OMR_TRACKER_STATUS_MSG=""
 							OMR_TRACKER_STATUS="OK"
 						fi
 						if [ "$serverip_ping" != false ] && [ "$OMR_TRACKER_STATUS" = "OK" ] && [ "$OMR_TRACKER_TYPE" != "httping" ] && [ "$OMR_TRACKER_SERVER_HTTP_TEST" = "1" ]; then
@@ -444,16 +510,28 @@ while true; do
 							config_foreach _httping_server server $OMR_TRACKER_DEVICE_IP
 							if [ "$serverip_ping" = false ]; then
 								#OMR_TRACKER_STATUS="ERROR"
-								OMR_TRACKER_STATUS_MSG="No access to server API"
+								OMR_TRACKER_STATUS_MSG="$OMR_TRACKER_STATUS_MSG No access to server API"
 							else
 								OMR_TRACKER_STATUS_MSG=""
 								OMR_TRACKER_STATUS="OK"
 								break
 							fi
+						elif [ "$serverip_ping" = false ] && [ "$OMR_TRACKER_STATUS" = "OK" ] && [ "$OMR_TRACKER_SERVER_TEST" = "1" ]; then
+							if [ "$OMR_TRACKER_TYPE" = "ping" ]; then
+								_ping_server_all
+							fi
+							if [ "$OMR_TRACKER_TYPE" = "httping" ]; then
+								_httping_server_all
+							fi
+							if [ "$server_ping" != false ] && [ "$servers" = true ]; then
+								OMR_TRACKER_STATUS_MSG="$OMR_TRACKER_STATUS_MSG No answer from server"
+								OMR_TRACKER_STATUS="ERROR"
+								break
+							fi
 						fi
 						[ "$OMR_TRACKER_STATUS" = "OK" ] && break
 					elif ! $(exit $status); then
-						OMR_TRACKER_STATUS_MSG="gateway down"
+						OMR_TRACKER_STATUS_MSG="IPv4 gateway down"
 					fi
 					tries=$((tries - 1))
 					#_restart
@@ -488,7 +566,7 @@ while true; do
 						break
 					elif [ "$OMR_TRACKER_TYPE" != "none" ]; then
 						if ! $(exit $status); then
-							OMR_TRACKER_STATUS_MSG="gateway6 down"
+							OMR_TRACKER_STATUS_MSG="IPv6 gateway down"
 						fi
 						serverip_ping=false
 						if [ "$OMR_TRACKER_TYPE" = "ping" ]; then
@@ -535,9 +613,6 @@ while true; do
 									fi
 									OMR_TRACKER_STATUS_MSG="check error"
 								fi
-							else
-								OMR_TRACKER_STATUS_MSG=""
-								OMR_TRACKER_STATUS="OK"
 							fi
 						else
 							OMR_TRACKER_STATUS_MSG=""
@@ -555,10 +630,22 @@ while true; do
 								OMR_TRACKER_STATUS="OK"
 								break
 							fi
+						elif [ "$serverip_ping" = false ] && [ "$OMR_TRACKER_STATUS" = "OK" ] && [ "$OMR_TRACKER_SERVER_TEST" = "1" ]; then
+							if [ "$OMR_TRACKER_TYPE" = "ping" ]; then
+								_ping_server_all
+							fi
+							if [ "$OMR_TRACKER_TYPE" = "httping" ]; then
+								_httping_server_all
+							fi
+							if [ "$server_ping" != false ] && [ "$servers" = true ]; then
+								OMR_TRACKER_STATUS_MSG="$OMR_TRACKER_STATUS_MSG No answer from server"
+								OMR_TRACKER_STATUS="ERROR"
+								#break
+							fi
 						fi
 						[ "$OMR_TRACKER_STATUS" = "OK" ] && break
 					elif ! $(exit $status); then
-						OMR_TRACKER_STATUS_MSG="gateway down"
+						OMR_TRACKER_STATUS_MSG="IPv6 gateway down"
 					fi
 					tries=$((tries - 1))
 					#_restart
@@ -599,22 +686,21 @@ while true; do
 		fi
 	fi
 	if [ "$OMR_TRACKER_CHECK_QUALITY" = "1" ]; then
-		if [ "$OMR_TRACKER_PREV_STATUS" = "OK" ]; then
-			if [ -n "$OMR_TRACKER_LOSS" ] && [ "$OMR_TRACKER_LOSS" -ge "$OMR_TRACKER_LOSS_FAILURE" ] && [ "$OMR_TRACKER_STATUS" = "OK" ]; then
+		if [ "$OMR_TRACKER_PREV_STATUS" = "OK" ] && [ "$OMR_TRACKER_STATUS" = "OK" ]; then
+			if [ -n "$OMR_TRACKER_LOSS" ] && [ -n "$OMR_TRACKER_RECOVERY_LOSS" ] && [ "$OMR_TRACKER_LOSS" -ge "$OMR_TRACKER_FAILURE_LOSS" ]; then
 				OMR_TRACKER_STATUS="ERROR"
-				OMR_TRACKER_STATUS_MSG="Packet loss is $OMR_TRACKER_LOSS this is more than limit defined at $OMR_TRACKER_LOSS_FAILURE"
-			fi
-			if [ -n "$OMR_TRACKER_LATENCY" ] && [ "$OMR_TRACKER_LATENCY" -ge "$OMR_TRACKER_LATENCY_FAILURE" ] && [ "$OMR_TRACKER_STATUS" = "OK" ]; then
+				OMR_TRACKER_STATUS_MSG="Packet loss is $OMR_TRACKER_LOSS this is more than failure limit defined at $OMR_TRACKER_FAILURE_LOSS"
+			elif [ -n "$OMR_TRACKER_LATENCY" ] && [ -n "$OMR_TRACKER_FAILURE_LATENCY" ] && [ "$OMR_TRACKER_LATENCY" -ge "$OMR_TRACKER_FAILURE_LATENCY" ]; then
 				OMR_TRACKER_STATUS="ERROR"
-				OMR_TRACKER_STATUS_MSG="Latency is $OMR_TRACKER_LATENCY this is more than limit defined at $OMR_TRACKER_LATENCY_FAILURE"
+				OMR_TRACKER_STATUS_MSG="Latency is $OMR_TRACKER_LATENCY this is more than failure limit defined at $OMR_TRACKER_FAILURE_LATENCY"
 			fi
-		elif [ "$OMR_TRACKER_PREV_STATUS" = "ERROR" ]; then
-			OMR_TRACKER_STATUS="ERROR"
-			if [ -n "$OMR_TRACKER_LOSS" ] && [ "$OMR_TRACKER_LOSS" -le "$OMR_TRACKER_LOSS_RECOVERY" ] && [ "$OMR_TRACKER_STATUS" = "OK" ]; then
-				OMR_TRACKER_STATUS="OK"
-			fi
-			if [ -n "$OMR_TRACKER_LATENCY" ] && [ "$OMR_TRACKER_LATENCY" -ge "$OMR_TRACKER_LATENCY_RECOVERY" ] && [ "$OMR_TRACKER_STATUS" = "OK" ]; then
-				OMR_TRACKER_STATUS="OK"
+		elif [ "$OMR_TRACKER_PREV_STATUS" = "ERROR" ] && [ "$OMR_TRACKER_STATUS" = "OK" ]; then
+			if [ -n "$OMR_TRACKER_LOSS" ] && [ -n "$OMR_TRACKER_RECOVERY_LOSS" ] && [ "$OMR_TRACKER_LOSS" -ge "$OMR_TRACKER_RECOVERY_LOSS" ]; then
+				OMR_TRACKER_STATUS="ERROR"
+				OMR_TRACKER_STATUS_MSG="Packet loss is $OMR_TRACKER_LOSS this is more than recovery limit defined at $OMR_TRACKER_RECOVERY_LOSS"
+			elif [ -n "$OMR_TRACKER_LATENCY" ] && [ -n "$OMR_TRACKER_RECOVERY_LATENCY" ] && [ "$OMR_TRACKER_LATENCY" -ge "$OMR_TRACKER_RECOVERY_LATENCY" ]; then
+				OMR_TRACKER_STATUS="ERROR"
+				OMR_TRACKER_STATUS_MSG="Latency is $OMR_TRACKER_LATENCY this is more than recovery limit defined at $OMR_TRACKER_RECOVERY_LATENCY"
 			fi
 		fi
 	fi
